// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed icon.png
var appIconData []byte
var appIcon = &fyne.StaticResource{
	StaticName:    "icon.png",
	StaticContent: appIconData,
}
